name: pytorch_gpu_3.9
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libavif_api=1.1.1=h57928b3_3
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=he0c23c2_0
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - brotli-python=1.1.0=py39ha51f57c_3
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h2b77a98_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - double-conversion=3.3.1=he0c23c2_0
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=7.1.0=gpl_h2585aa8_705
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.42.12=hed59a49_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.0.0=h9e37d49_0
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.12=hbb528cf_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.1.1=h4d049a7_2
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.3=default_ha2db4b5_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblapacke=3.9.0=35_h3ae206f_mkl
  - libopencv=4.11.0=qt6_py39h30291f0_602
  - libopenvino=2025.0.0=hb1d9b14_2
  - libopenvino-auto-batch-plugin=2025.0.0=h04f32e0_2
  - libopenvino-auto-plugin=2025.0.0=h04f32e0_2
  - libopenvino-hetero-plugin=2025.0.0=hb61b842_2
  - libopenvino-intel-cpu-plugin=2025.0.0=hb1d9b14_2
  - libopenvino-intel-gpu-plugin=2025.0.0=hb1d9b14_2
  - libopenvino-ir-frontend=2025.0.0=hb61b842_2
  - libopenvino-onnx-frontend=2025.0.0=h6e6c283_2
  - libopenvino-paddle-frontend=2025.0.0=h6e6c283_2
  - libopenvino-pytorch-frontend=2025.0.0=he0c23c2_2
  - libopenvino-tensorflow-frontend=2025.0.0=ha83d810_2
  - libopenvino-tensorflow-lite-frontend=2025.0.0=he0c23c2_2
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=5.28.3=h8309712_1
  - librsvg=2.58.4=h5ce5fed_3
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.3=hfa2b4ca_0
  - mkl=2024.2.2=h57928b3_16
  - munkres=1.1.4=pyhd8ed1ab_1
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.11.0=qt6_py39h52b2171_602
  - openexr=3.3.2=h974021d_0
  - openh264=2.5.0=ha9db3cd_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h0c53d3b_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h99c9b8b_2
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - py-opencv=4.11.0=qt6_py39h2b3f752_602
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.9.23=h716150d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.3=h72a539a_1
  - rav1e=0.6.6=h975169c_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=78.1.1=py39haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sqlite=3.50.2=hda9a48d_1
  - statsmodels=0.14.5=py39h9e4d2f2_0
  - svt-av1=2.3.0=he0c23c2_0
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.15=hf199647_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.23.0=py39h0802e32_3
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - altair==4.2.2
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - click==8.1.8
      - distro==1.9.0
      - edge-tts==7.2.3
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - fastapi==0.118.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - numpy==1.26.4
      - openai==2.1.0
      - opencv-python==4.7.0.72
      - pandas==2.3.3
      - pillow==9.5.0
      - propcache==0.4.1
      - protobuf==3.20.3
      - psutil==7.1.0
      - pyarrow==21.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - pympler==1.1
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - pywin32==311
      - pyyaml==6.0.3
      - referencing==0.36.2
      - rich==14.2.0
      - rpds-py==0.27.1
      - scikit-learn==1.6.1
      - sentry-sdk==2.41.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.48.0
      - streamlit==1.22.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - toolz==1.0.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tornado==6.5.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - ultralytics==8.0.98
      - uvicorn==0.37.0
      - validators==0.35.0
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - yarl==1.22.0
prefix: C:\Users\Dream Machine\.conda\envs\pytorch_gpu_3.9
